[build]
command = "npm install && npm run build"
functions = "functions"
[functions]
external_node_modules = ["express"]
node_bundler = "esbuild"
[[redirects]]
force = true
from = "/fitness/*"
status = 200
to = "/.netlify/functions/fitness/:splat"
[[redirects]]
force = true
from = "/images/*"
status = 200
to = "/public/images/:splat"